### ISSUE TITLE
hook入口函数的改良建议

### ISSUE THREAD

**Issue by luomoxu** [Lama3L9R/ArtifactoryKeygen#2]
我自己也搞了个agent来实现这个功能，本来打算自用的
偶然搜索到了这个项目，简单看了看代码
目前hook的入口是几个license相关类，但是随着版本升级，代码重构的话，需要hook的类名，方法名，变量名是可能发生变化的，目前这种处理方式的兼容性略差
再研究研究代码就会发现几个license类关于公钥的处理都需要调用base64相关的类
所以可以将hook的入口修改为Base64的类，判断传入的字符串为原始公钥的时候，返回修改后公钥
这个操作基本上可以兼容后续大部分的版本变更

**Comment by Lama3L9R** [comment]
支持，这代码写的实在是太烂了，我准备有空重写一下，直接毙了kt来减小体积

**Comment by luomoxu** [comment]
> 支持，这代码写的实在是太烂了，我准备有空重写一下，直接毙了kt来减小体积
> 
> 不使用B64的原因是为了防止运行时其他调用B64的地方性能下降

性能影响其实还好 只是加了一个判断逻辑，在当前的主流CPU性能下，影响微乎其微，而且base64的操作并没有想象中的调用那么频繁

**Comment by luomoxu** [comment]
> 支持，这代码写的实在是太烂了，我准备有空重写一下，直接毙了kt来减小体积
> 
> 不使用B64的原因是为了防止运行时其他调用B64的地方性能下降

性能影响其实还好 只是加了一个判断逻辑，在当前的主流CPU性能下，影响微乎其微，而且base64的操作并没有想象中的调用那么频繁

**Comment by pierai** [comment]
> 我自己也搞了个agent来实现这个功能，本来打算自用的 偶然搜索到了这个项目，简单看了看代码 目前hook的入口是几个license相关类，但是随着版本升级，代码重构的话，需要hook的类名，方法名，变量名是可能发生变化的，目前这种处理方式的兼容性略差 再研究研究代码就会发现几个license类关于公钥的处理都需要调用base64相关的类 所以可以将hook的入口修改为Base64的类，判断传入的字符串为原始公钥的时候，返回修改后公钥 这个操作基本上可以兼容后续大部分的版本变更



> 我自己也搞了个agent来实现这个功能，本来打算自用的 偶然搜索到了这个项目，简单看了看代码 目前hook的入口是几个license相关类，但是随着版本升级，代码重构的话，需要hook的类名，方法名，变量名是可能发生变化的，目前这种处理方式的兼容性略差 再研究研究代码就会发现几个license类关于公钥的处理都需要调用base64相关的类 所以可以将hook的入口修改为Base64的类，判断传入的字符串为原始公钥的时候，返回修改后公钥 这个操作基本上可以兼容后续大部分的版本变更

老哥有完整的部署&破解方案吗？
